layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name
    
social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
    hackerrank: bharathreddyspi
    instagram: bharathreddyspi
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
    twitter: Bharath52988649
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: GSOC
    web_url: https://summerofcode.withgoogle.com/
    image_url: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASMAAACtCAMAAADMM+kDAAAApVBMVEX////7vAX7ugD7uABsbGxvb29paWlnZ2f81IL84Kf81Yb8/Pz94q5xcXH4+PiCgoKdnZ3t7e2VlZW6urqnp6fg4OB6enrn5+fU1NTDw8PKysrz8/OKiora2tpiYmL++OyRkZH98NX7vh3+/Pavr6/83Jz96cH7x0/97Mv95bn7wzn+9ub80nz7zmv97M782pb7ylv7xUb+8tz80XX7xkr7zGL7wC0Xmct4AAANM0lEQVR4nO1cCXujLBdNELGpxT0mRrPbfZlOOu3//2nfvSAuiWmb6Tsz/ZTzPG2igMLxblwwg4GGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGxjfFcvP0r7vw3bHcEEOT9C6AoqEm6V0gRcMhIet/3ZHvC0kRkGRoko5AUaRJOoqKIk3SEdQp0japFU2Khtq7HWKfIk3SAQ4p0jZpD20UaZvUQEERIYYCIaTH6rYbHUJMQIzh9cPl7c16t765Gp09b4AoYK2l9s2/HsIfx8g4BBD083K9bdSzdxfPxCAttR/+Uc//Hi6MQ9u8ubxvrbu8uDMODBU5+8s9/vvY54gYd1fvVH963mepfxwZb7dV2XJ3czG6HF1c7ZbVyaefRq85Isa5XZzfXp3d1fza28tFydOIkP5yRMq87NMj2OfmfM0wnpWI3ddFqV8cGc+FK7t9OzTNQsqGo6LVmdFPjoxisE8tzqussylkaVQ26xNHxg9xvH04zpCQpedls12POCoo2r0dxEv7LBEZG9wafeOoULSrd4VISdxlvWVvOCLP4mD0kRAN64SeG33iiGyER/skRSVJ16RHHMmcx9VnKVLqtuwRR8Y5ftt9niJoImIAtNv94Ehq2vbtE+a6AhGpgWfSE46kTDycIkbA0TU2AtnrBUfkDT+fjlJECCEtImZcYLNH0guODBETvqNpULptYZCght4b3edouSEb/Lw9LkaPg3aXJy39c+dXS3ALlpiE3B2fxuJc/7w1D4CCBJF5t9fdcJHIQAd1YI0qCyQY+EXqp+rs2RvSaUkSu9R+4rfH/ST12640UCAtW6Ro/Ws/9X2HTR86vdNNLDWKiHm7LyGv9kDtz0Ifv8ZYcVnPrMlqu4E0VZ1VN7kaK0bXNMnSRCmO0DJfGjJovGimBUS9bYe3A6oFazS8583UtVh5LTgSkcErEXIEMWNzU5KII392liRFkRhm3asZP0WicakO8Wgj7JFo99oQOST4QV6oezap3A6KK9HbOkVyaXqtytEu38tEkcw/Xtb0TRgklWvrmk0qN88Ik1LN+ImcYVSGh7wMygCzSOfe1OICnOkpY9Yxdav2F4lR3pT5+81OlL9UiyXI2YMiVC4uLe/KdQJ0iiXDnSKptgVLmGQ1EUGXD7iv5f2FNpWhEhlKFlQQIJzesiaFnbFJ9V1qYlQq7y8mYIOrRkA9aExoiSFXIZUNetgv7gpJ9Sm+MLRFHlsO8LYeA4m1gJu6KyuytAVHaK3qOQFibN+58f8R1nXPhBwpOZIy0nBcaKZ/1Egosv037XJUJJW6gDU5Yo+ksj0Nq2IUrefykBC5lD1qt0dFRrMbqEhq+jXjWsaP1+UJVJ2KsTfp9h7b/VqHpAhRkrQ3SrKRjuu80KW7eqnxKIzN/V1FSj0+6pQUIZRNEpnWZf3lGWmUpOUWpeWOALmEXXd7dWvWOYpKSZKL2A1P9yjKd+WwX2qT21LCCkZRNc9IRymq1K2aliqS7sTSmUgu4bdiwiv42F43KBL5ObGi3TFbpCBJEoF0M+Mvd89gjhJXlZTbwvzRupEakW5NToi7KEUIYZOE/Vk2hi6DAOTodVCbsi7B5TfrCXMkUuFdpUhKkkwgPe+TdL0EG9VYEiH3L0azkly8xPLuUlSQhHbmYP2MbDa1JRGBg1VKmStBLjtpixRA3aSzb38Za1tfDjioIVKUT0anpQgBkiQ0pm17Vrkk0g4xWRs8kq5TJN47qqf4GyT8GLy3t02I0dIgfXjvSFrtlhV9cnd9fb05SpGwRmf92DcylIL02iJIrZtqijKhosue7D8q1qSXh0b5PchVkMe+7GMrZqs3Ry1PG0Uj1aQnHA2JyAt9eusxUIRJ2sFWrE32hSOhbc05/bsUyS3vjz3ae6zk4rMkGa+i9qhX+/zLBNrlp94XkRHRVc/eFynzP1fHvX0Blal8UnPd/nCkSFpev69vxpvMeJcZ8T5xpNRtcDE8zlKxw7T+ElevOFJ2ZrD9MTzyPi15KF7Ovuzp+7RA0q/i9yG2oztjjyZiGG8/Coa2j7VGPeMIJmhltmx3eU3kD9bIn6+5+1FunLlpbvjrGUe406+2h2h3Ozo/ezg7v7yt/UDL/WNTwvrHEejU63s7re4PXtvuIUfi9fSrIztkbh4Pw6cecDSSJqcJY/hyQJN9c/7WWrf7ecinh/MDEPE7Wm8vo6v17n55v1vfXDygoyMQHhxUPut8OrsVMoaW/oyoD2HRO71IdBrW7bM2TVEd67ZAW1PURAtJ3V9HOxUH6qal6BB7JGmK2tBQN01RO+pblLUtOoJq962WoqNY69DxY8jtgJqidwGSpG3RR1gTLUUfYvlxFQ0NDQ0NDQ0NDQ0NDQ0NDQ2N7wFnFmXuKpqf1CidTP5Qd74jQk5Nk5smc09hKVwsnLbzzizPp3ZbyX8Jfz6u3cOeh1E+be2O7NPE/9LdnIxyGgfeilNuzT7fLjRpW6cSygB8+qU+fYQ0sywrVUd2bjKB6BhL00XwldvZmWm6c3wmTmJm6Yf1S7RzNLXMIEkCyk5T3BORUTcP1UHqMroKZ0nEWXxEXKbM+8rtIspLjicnUHSEI5eKvoeL1Vc69QHGLK4UzXapKy1juqLj9gZf48i3uPt7LVs5cpgpTtp/VNemrKY6EXUVYfYxL/I1jnJO27QCnFZFgDOpCRgcyC4pjpx6VdukVT/T1C4+5d84maEu+LNEPG4HiiflKdUL+CqNLxb703kpMOlU1h3YzowFTlrc1KdsX8EcqFn2QtxUcTROkiOS9h5cHh/6oEnAKeWevLfv4UEgb+pEcBBPAzcvOHKiGErz8hoejUvOY9l7fwGSGlhjz7KYmQwitmBCDjxrGsEpUM6cLiyW4aBtj4I15gl8jaxpTi2mrhxyKKABUD1jHEAjeT5h++a4qgn3zhjcIpIcTcSBeypLdmmNxjMJUJIp5SaFcMDEq40hKIADTlF7/BgP4MiMJEepPEEzdUHHpSxL0kOOTNfMk8A0PctLQHjBakWmS/PEw1MrPIWDzlgcJh5lCRYHlhsoyxwxCu1iGjuDqQsPNoOnJB8K1q2jrInSy6kbJnAdEzjyTbZKwhVlJ8Z1KeWRuhcVsGwfnlPiT0LKuTNw4ImFvp8ALT5KHc0nfgIlBUcQMOR+msD/kvWQgxf20hpHFnLEOXZtxRmOekZjGAwXJtaT7MwptQchy1Bu5nhpcFPV6OcWx7r2iqJAzGuyk7Gm6Zszs6oZUFFxBkoB92aikznLBifBNpUceRYyBIxg3+fyyvC0Q9MUMdOcgujMqCme65RKjuwxM/G+Y5cvKotlT2HY2NEGR5LFhArVdjgDEsR44WLSrmHtuLBmEdAT0ZoSBQVfKTPTps3e5yiQjhVEyHL84tJgAbzBxIpljfjAgH2ATNmj1AekHhy6ijaXZ1BeuL0Vj+GRc1nZlbpm45+TQHzCo0bY4K9MuGyDIzmUYnR2zFIgQrA/ZvIOLpukJncFYhCtqCZGor7shjVvcuSxMlASEPIuarJ5WQ/tEciuvDhnJzrd3KT1FhkPHG4qVQfCYu6piiaUFmLqUclRxGNQCeYm+4EVDGoOUlHjyJqrzspip+IoUxxNaMGR6zY5cji1FSWzJkezpuo4lDuq5nTGCkMytjwUYXXxEzlKGY8r1w1GIbHRIAsEIEOlUEXcrIQqKDjKQTeZVwse0nBejeVkjkCOqku1y1G2L0cpb4b0pRxlKEcr+V3IkSLsdOSUZ4qkCeemXapfykGGQL0KJwUyBLIk7IVT2GwbDJOwzgMlR+EiUz2cwqiFm03oZzmCPzlejLjqHJVWBvzJnj0CO1/OQGyIUDxV02ROSqnsmAd+DZpKWfyNCCkweTxDltLQ5NjtGTM9uJqzwic0Z3zlYNzC6WyAuoA39ZRfc2LuYgcTsxgPKEVkC17AtnrCKPsx/zRHiRzvBIWhwRH4NWyfZsIHNjgC/uKZGP3cZTH6NazpiJoeXcnecOHkPHGwONGvYX89BjP+bJXBf9mtFcxyoyjmYogeBZsTuaa5GqDfBNmK3Mr3zyw8kUFAVcjinFGonlErQStgZmHO3c9zBIaWRyGYuGhPjkTUE0YiPsKJcyNuDBiLvdxzwTD62MeqZgofebiyMoyPUhNnwgG1fmeeNIuZiShDUI9h2FjobyQOLPEMQLAhZmSZixxZmD+aYcRgsiphMFlZjFmxGH5CmbUIfHS6q4WMJxaSI4wVvIXkaFH4tQXqcY5xtogwokUjOEwwemaeeBTTvRnzFAJovGl4UDNdwXcrH4vbyoP4N6eS89wLvLBS1HEeeLkKRyd5EOSqzIeSZJCBWZ/MhISnoRdEjdv603K25Iivti3/kJzys/m9+oAmc6deVcGez6bqSdj786d0OptO2mpCN/F70QC69hvW6ERI62jHNPygYm/hrywh/wk9lqjRgBCc5eMxhgv/uivfF3Leb5rHcqIaACcHluLolJxuD2H7/h9fGNLQ0NDQ0NDQ0NDQ0NDQ0NDQ0PiG+B9oI+32djVgPgAAAABJRU5ErkJggg==

theme: jekyll-theme-cayman
